### ISSUE TITLE
Get "boards.txt not found" error

### ISSUE THREAD

**Issue by boda-akos** [nulllaborg/nulllab_w80x_arduino#1]
Copied all files in "Arduino/hardware/". If I copy "boards.txt" in all subdirectories, then the board(s) appear in "Tools/Board Manager" but still get compile errors. Must admit, I am not a bright Arduino system programmer. Could you tell me how to install it ? thanks.

**Comment by nulllaborg** [comment]
Fix it ,but  you can try it
